### ISSUE TITLE
Deciding a project

### ISSUE THREAD

**Issue by jakepruitt** [jakepruitt/capstone#1]
Hello Team!

This issue will be used to keep track of deciding on the project we are working on. Please post your top five choices for projects you would like and top three projects you would not like to use.

Also, if you could watch this repository (button in top right), you will get notifications whenever a new issue is created. cc/ @jwward2 @hmthomas93 @lshart @jmitre

**Comment by lshart** [comment]
Top picks
1) Hardware AI: Hidden Markov Model Learning and Evaluation Engine by Garvey
2) S​ustainability Game: Modeling and Simulating Systems by Montiel
3) Fulton Schools of Engineering Tutoring Centers: Student Service Management Program by Graham
4) Social Savvy – A Predictive Analytics “Game” by Cornell (cornell1)
5) Social Graphs and 3rd party Content Matching Data Processing by Zula

Top Nix
1) Zinnect iOS Application by Zinnect
2) Cross-Platform In-App Purchase Validation and Content Delivery Server (in file IAPSupportServer...)
3) SignAid: Automated Translator of Sign Languages by Ahn

**Comment by hai1337** [comment]
Virtual Reality Passenger Sight System (VRPSS) - Smith
Dr. Discovery - Nelson
Affect-Driven Adaptation in Cognitive Systems - Atkinson2
Collective Reaction - Atkinson
S​ustainability Game: Modeling and Simulating Systems - Montiel

**Comment by jwward2** [comment]
Top Picks:
1) Dr. Discovery Content Dashboard
2) Atkinson: Collective Reaction
3) Atkinson: Affect-Driven Adaptation in Cognitive Systems
4) ​Zinnect iOS Application
5) ITSM predictive analytics mobile application

Worst Pickst:
1) Employee Self Service – ESS Application
2) Sparkys Dash
3) A Predictive Analytics “Game”
4) “Feature Flag Console for Choice Hotels International”
5) SignAid: Automated Translator of Sign Languages

**Comment by ghost** [comment]
1) Dr. Discovery Content Dashboard
2) Atkinson: Collective Reaction
3) Virtual Reality Passenger Sight System (VRPSS) - Smith
4) Runger or Runger 3
5) Zinnect

**Comment by jakepruitt** [comment]
1. Augmenting Tweets with Expert Data for Crisis Response (because maps + lots of data = :heart: )
2. Runger or Runger3 (mostly for OpenCV library experience)
3. Garvey Hidden Markov Model Learning - Mostly for Markov chain probabilistic analysis
4. Atkinson data processing - because cloud data processing is how I earn money for food.
5. Dr. Discovery Content Dashboard - Mostly interested in backend

Worsts:
1. Anything that mentions Powershell or C# or ASP.NET is a no
2. Sparys Dash
3. Optimal seating arrangements
4. Allstate
5. Anything describing itself as "Airbnb and Uber meets Elderly Care".

**Comment by jakepruitt** [comment]
More detail this time, specifically for the proposal:
1. **Atkinson.docx - Adaptive Data Framework and Affect Bot** Personally, I have a lot of experience designing, implementing, and optimizing cloud-based data-processing pipelines and services, especially with noSQL databases. I've also had experience with artificial intelligence methods, and implementing them sounds fantastic. As a team, I think we'd be able to split work into statistical analysis (which @jwward2 is very good at), infrastructure (which I can take on), and game design with affect in mind (which @hmthomas93 has experience with, I think).

-1. **PrimeTime ...  Best described as UBER meets AirBnB for senior citizen healthcare.** - sounds like a terrible subject.

**Comment by jakepruitt** [comment]
We have a project assigned!
