### ISSUE TITLE
First email and first meeting

### ISSUE THREAD

**Issue by jakepruitt** [jakepruitt/capstone#3]
After everyone has put their information in the wiki, we will figure out what times work best for a meeting next week. We will then send an email to the professor as our first contact! This is what I'm thinking for the format of the email:
- Introductions
- Links to slack/github/bios
- Meeting time

cc/ @jwward2 @hmthomas93 @ralbaya1

**Comment by jwward2** [comment]
Hi Everyone, 

After looking over the group availability it seems we can meet as follows:

#### Group Availability

| Day | Hours |
| --- | --- |
| Tues | 9:00 - 16:00 |
| Thurs | 9:00 - 16:00 |
| Fri | 15:00 - 7:00 (preferred option for weekly meeting with sponsor) |
| Sat | all day (preferred group meeting day) |
| Sun | all day (preferred group meeting day) |

Please let me know if there is any issue with the noted, preferred days and if there is any preference between Saturday and Sunday.

**Comment by jakepruitt** [comment]
Looks great! Friday would work well for all of us to go to meet the sponsor. Thanks for drafting that up. I have no preference between sat and sun.

**Comment by ralbaya1** [comment]
Same For me I do not have any preference between sat and sun, and Friday is convenient to meet the sponsor after class.

**Comment by hai1337** [comment]
Friday is definitely preferred for our sponsor meeting so I do not need to take off work. As for Saturday and Sunday, I prefer Sunday but am open to Saturday.
